version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - quiz-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/data/history:/app/src/data/history
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge